RPM & DEB packaging
endreszabo/PowerDNS-Dynamic-Reverse-Backend pull request #2
Opened 2019-11-09 06:40 UTC by bevhost

2019-11-11 15:51 UTC, endreszabo requested changes
Thanks for the effort you put in :)

Pls check my comments.

2019-11-11 15:51 UTC, endreszabo commented on pdns-dynamic-reverse-backend.py
> +Copyrught (c) 2019 David Beveridge (bevhost)
You have a typo here.

2019-11-11 15:51 UTC, endreszabo commented on pdns-dynamic-reverse-backend.py
> +CONFIG = '/etc/pdns/dynrev.yml'
You passed this file path as argument in config `pipe-handler` option. Use that (`argv[1]`) instead IMO.

2019-11-11 15:51 UTC, endreszabo commented on pdns-dynamic-reverse-backend.py
> +
This is an extra newline.

2019-11-11 15:51 UTC, endreszabo commented on Makefile
> +	$(INSTALL) -pm 750 pdns-dynamic-reverse-backend.py $(DESTDIR)$(BINDIR)/pdns-dynamic-reverse-backend.py
You defined perms as `750`. User running `pdns_server` will not be able to access it.

2019-11-14 08:33 UTC, bevhost commented
Please check out my latest commits

2019-11-14 12:16 UTC, endreszabo commented
Well done, thank you for all the efforts you put in this PR.

2019-11-14 12:16 UTC, merged